name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android
        run: flutter build apk --release --target-platform android-arm64

      - name: Build Windows
        run: flutter build windows --release

      - name: Build Web
        run: flutter build web --release

      - name: Build Linux
        run: flutter build linux --release

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
